### ISSUE TITLE
Public Release Epic

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#38]
- [x] Loosen dependency version requirements
- [x] Use GitHub actions
- [x] Add warning if binaryTargets option is used
- [x] Add contributing docs (postgres uri required)
- [x] Add ARCHITECTURE.md (look at esbuild)
- [x] #36
- [x] type check tests with pyright
- [x] move package to src directory
- [x] add makefile
- [x] add support for filtering by relations
- [x] ensure all tests have docstrings (see blog post)
- [x] add option to enable logging queries
- [x] make pytest-pyright public
- [x] online runnable example, gitpod? (Also add to docs and readme)
- [x] create a template repository
- [x] #34
- [x] rename master to main
- [x] test typesafety on CI
- [x] update readme
- [x] add attributions

Docs
- [x] add badges to readme and docs
- [x] document action methods
- [x] document raw queries
- [x] switch quickstart to pyright
- [x] indent schemas to 2 spaces not 4
- [x] add filtering by types and relations to the common operations page
- [x] add features and roadmap to readme and docs
- [x] command line
- [x] version guarantees
- [x] windows is not supported
- [x] rename reference/common to operations or similar

Release order
- [x] Update all install messages to use PyPi
- [x] Public repo
- [x] add read the docs config
- [x] Publish to read the docs
- [x] Update references to docs website
- [x] Publish to PyPi
- [x] Create a GitHub release, go to [https://github.com/RobertCraigie/prisma-client-py/releases](https://github.com/RobertCraigie/prisma-client-py/releases)
- [x] make templates and quickstart repository public
- [x] Update template and quickstart repository to link to docs website

Documentation references to update:
- [x] https://github.com/RobertCraigie/prisma-py-async-quickstart
- [x] repo link
