### ISSUE TITLE
Upgrade Prisma to V4

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#562]
This issue is being used to track compatibility with Prisma V4

- [x] New CLI architecture, #454 
- [ ] New internal Query Raw architecture, #484 
- [ ] Check if broken MySQL test is fixed
